namespace: voting

frontend:
  image:
    repository: acraksvoterdev.azurecr.io/azure-vote-front
    tag: "1.0"
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
  env:
    redisHost: redis
    redisPwd: ""

redis:
  image:
    repository: redis
    tag: "7.2"
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
  storage:
    size: 1Gi
    storageClassName: managed-csi

ingress:
  enabled: true
  className: nginx
  path: /

hpa:
  minReplicas: 1
  maxReplicas: 4
  cpuUtilization: 70

rbac:
  adminGroupObjectId: ""